name: roguelike
description: Roguelike built with Phaser and Dart.
dependencies:
  build: ^0.6.3
  code_builder: ^1.0.0-alpha+7
  phaser: ^2.6.2
  source_gen: ^0.5.2
dev_dependencies:
  barback: ^0.15.2
  build_barback: ^0.0.3
  build_runner: ^0.1.1
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.0
transformers:
- dart_to_js_script_rewriter
